[package]
name = "rslint_scoping"
version = "0.1.0"
edition = "2018"
autobins = false
build = "src/build.rs"

[features]
default = []
flatbuf = ["flatbuffers", "differential_datalog/flatbuf", "types/flatbuf"]
profile = ["cpuprofiler"]
ovsdb = []
command-line = []
nested_ts_32 = ["differential_datalog/nested_ts_32"]
c_api = ["differential_datalog/c_api", "types/c_api"]

[target.'cfg(not(windows))'.build-dependencies]
libtool = "0.1"

[dependencies.differential_datalog]
path = "./differential_datalog"

[dependencies]
abomonation = "0.7"
time = { version = "0.2", features = ["serde"] }
ordered-float = { version = "2.0.0", features = ["serde"] }
cpuprofiler = { version = "0.0", optional = true }
#differential-dataflow = "0.11.0"
differential-dataflow = { git = "https://github.com/ddlog-dev/differential-dataflow", branch = "ddlog-2" }
#timely = "0.11"
timely = { git = "https://github.com/ddlog-dev/timely-dataflow", branch = "ddlog-2" }
fnv = "1.0.2"
once_cell = "1.4.1"
libc = "0.2"
num-traits = "0.2"
num = { version = "0.3", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
erased-serde = "0.3"
crossbeam-channel = "0.5.0"

# FlatBuffers dependency enabled by the `flatbuf` feature.
# flatbuffers crate version must be in sync with the flatc compiler and Java
# libraries: flatbuffers "0.6" <-> FlatBuffers "1.11.0".
flatbuffers = { version = "0.6", optional = true }

[[bin]]
name = "rslint_scoping_cli"
path = "src/main.rs"
required-features = ["command-line"]

# [lib] section must be in the end

[lib]
name = "rslint_scoping_ddlog"
# Compiler will append the crate-type attribute here as well as the
# build profile and workspace definition
# crate-type = ["rlib", "staticlib"]

crate-type = ["rlib", "staticlib"]


[dependencies.types]
path = "types/"
[dependencies.types__ast]
path = "types/ast"
[dependencies.types__config]
path = "types/config"
[dependencies.ddlog_bigint]
path = "types/ddlog_bigint"
[dependencies.ddlog_log]
path = "types/ddlog_log"
[dependencies.ddlog_rt]
path = "types/ddlog_rt"
[dependencies.ddlog_std]
path = "types/ddlog_std"
[dependencies.debug]
path = "types/debug"
[dependencies.types__group]
path = "types/group"
[dependencies.types__inputs]
path = "types/inputs"
[dependencies.internment]
path = "types/internment"
[dependencies.types__outputs__no_unused_labels]
path = "types/outputs/no_unused_labels"
[dependencies.types__regex]
path = "types/regex"
[dependencies.types__scopes]
path = "types/scopes"
[dependencies.types__utils]
path = "types/utils"
[dependencies.types__variable_decl]
path = "types/variable_decl"
[dependencies.types__vec]
path = "types/vec"
